### ISSUE TITLE
Flow dev_org failing with Object Translations

### ISSUE THREAD

**Issue by mishraankit191** [SalesforceFoundation/Cumulus#3685]
[32m2018-10-05 16:00:38:[0m ---------------------------------------
[32m2018-10-05 16:00:38:[0m Initializing flow: config_dev
[32m2018-10-05 16:00:38:[0m ---------------------------------------
[32m2018-10-05 16:00:38:[0m
[32m2018-10-05 16:00:38:[0m Flow Description: Configure an org for use as a dev org after package metadata is deployed
[32m2018-10-05 16:00:38:[0m Steps:
[32m2018-10-05 16:00:38:[0m   deploy_post: Deploys all metadata bundles under unpackaged/post/
[32m2018-10-05 16:00:38:[0m   update_admin_profile: Retrieves, edits, and redeploys the Admin.profile with full FLS perms for all objects/fields
[32m2018-10-05 16:00:38:[0m Organization:
[32m2018-10-05 16:00:38:[0m   Username: <username>
[32m2018-10-05 16:00:38:[0m     Org Id: <orgid>
[32m2018-10-05 16:00:38:[0m Options:
[32m2018-10-05 16:00:38:[0m   namespace_inject: <namespace>
[32m2018-10-05 16:00:38:[0m   path: unpackaged/post
[32m2018-10-05 16:00:38:[0m   unmanaged: True
[32m2018-10-05 16:00:38:[0m
[32m2018-10-05 16:00:38:[0m Running task: deploy_post
[32m2018-10-05 16:00:38:[0m Beginning task: DeployBundles
[32m2018-10-05 16:00:38:[0m
[32m2018-10-05 16:00:38:[0m Deploying all metadata bundles in path <path>\unpackaged/post
[32m2018-10-05 16:00:38:[0m Deploying bundle: unpackaged/post/finalconfig
[32m2018-10-05 16:00:40:[0m Stripping namespace tokens from metadata for unmanaged deployment
[32m2018-10-05 16:00:40:[0m [31mTask failed: deploy_post[0m
[32m2018-10-05 16:00:40:[0m [31mFailing flow due to exception in task[0m
Traceback (most recent call last):
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 294, in _run_task
    task()
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\tasks.py", line 131, in __call__
    self.result = self._run_task()
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\tasks\salesforce\DeployBundles.py", line 36, in _run_task
    self._deploy_bundle(item_path)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\tasks\salesforce\DeployBundles.py", line 39, in _deploy_bundle
    api = self._get_api(path)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\tasks\salesforce\Deploy.py", line 64, in _get_api
   package_zip = self._get_package_zip(path)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\tasks\salesforce\Deploy.py", line 55, in _get_package_zip
    zipf_processed = self._process_zip_file(zipfile.ZipFile(zip_bytes))
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\tasks\salesforce\Deploy.py", line 68, in _process_zip_file
    zipf = self._process_namespace(zipf)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\tasks\salesforce\Deploy.py", line 102, in _process_namespace
    zipf, self.options["namespace_inject"], **kwargs
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\utils.py", line 216, in zip_inject_namespace
    content = content.replace(namespace_token, namespace_prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 44509: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\venvs\cci\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\python27\venvs\cci\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\venvs\cci\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\venvs\cci\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\venvs\cci\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\venvs\cci\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\venvs\cci\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\venvs\cci\lib\site-packages\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\cli\cci.py", line 1100, in flow_run
    handle_exception_debug(config, debug, no_prompt=no_prompt)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\cli\cci.py", line 1092, in flow_run
    flow()
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 214, in __call__
    self._run_step(stepnum, step_config)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 241, in _run_step
    self._run_flow(stepnum, step_config)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 269, in _run_flow
    flow()
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 214, in __call__
    self._run_step(stepnum, step_config)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 243, in _run_step
    self._run_task(stepnum, step_config)
  File "c:\python27\venvs\cci\lib\site-packages\cumulusci\core\flows.py", line 305, in _run_task
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 44509: ordinal not in range(128)

**Comment by davisagli** [comment]
What version of cumulusci do you have installed? (check using `cci version`)

**Comment by mishraankit191** [comment]
2.0.13

**Comment by davisagli** [comment]
Thanks for the report. This looks like a bug in CumulusCI so I have opened an issue in that project to track it: https://github.com/SFDO-Tooling/CumulusCI/issues/812

**Comment by mishraankit191** [comment]
Thank you!
